/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/state-tunnel'
import {
  Recipient,
} from './components/data-tunnel';


export namespace Components {

  interface DemoApp {}
  interface DemoAppAttributes extends StencilHTMLAttributes {}

  interface DemoCreateMessage {
    'getReceiverList': () => Promise<Recipient[]>;
    'sendMessage': (msg: string, recipients: Recipient[]) => Promise<void>;
    'setCreatingMessage': (createMessage: boolean) => void;
  }
  interface DemoCreateMessageAttributes extends StencilHTMLAttributes {
    'getReceiverList'?: () => Promise<Recipient[]>;
    'sendMessage'?: (msg: string, recipients: Recipient[]) => Promise<void>;
    'setCreatingMessage'?: (createMessage: boolean) => void;
  }

  interface DemoMessageLog {}
  interface DemoMessageLogAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'DemoApp': Components.DemoApp;
    'DemoCreateMessage': Components.DemoCreateMessage;
    'DemoMessageLog': Components.DemoMessageLog;
  }

  interface StencilIntrinsicElements {
    'demo-app': Components.DemoAppAttributes;
    'demo-create-message': Components.DemoCreateMessageAttributes;
    'demo-message-log': Components.DemoMessageLogAttributes;
  }


  interface HTMLDemoAppElement extends Components.DemoApp, HTMLStencilElement {}
  var HTMLDemoAppElement: {
    prototype: HTMLDemoAppElement;
    new (): HTMLDemoAppElement;
  };

  interface HTMLDemoCreateMessageElement extends Components.DemoCreateMessage, HTMLStencilElement {}
  var HTMLDemoCreateMessageElement: {
    prototype: HTMLDemoCreateMessageElement;
    new (): HTMLDemoCreateMessageElement;
  };

  interface HTMLDemoMessageLogElement extends Components.DemoMessageLog, HTMLStencilElement {}
  var HTMLDemoMessageLogElement: {
    prototype: HTMLDemoMessageLogElement;
    new (): HTMLDemoMessageLogElement;
  };

  interface HTMLElementTagNameMap {
    'demo-app': HTMLDemoAppElement
    'demo-create-message': HTMLDemoCreateMessageElement
    'demo-message-log': HTMLDemoMessageLogElement
  }

  interface ElementTagNameMap {
    'demo-app': HTMLDemoAppElement;
    'demo-create-message': HTMLDemoCreateMessageElement;
    'demo-message-log': HTMLDemoMessageLogElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
