/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';
import {
  SubscribeCallback,
} from './declarations';


export namespace Components {
  interface ContextConsumer {
    'context': { [key: string]: any };
    'renderer': Function;
    'subscribe'?: SubscribeCallback<any>;
  }
}

declare namespace LocalJSX {
  interface ContextConsumer extends JSXBase.HTMLAttributes {
    'context'?: { [key: string]: any };
    'renderer'?: Function;
    'subscribe'?: SubscribeCallback<any>;
  }

  interface ElementInterfaces {
    'ContextConsumer': Components.ContextConsumer;
  }

  interface IntrinsicElements {
    'ContextConsumer': LocalJSX.ContextConsumer;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {

  interface HTMLContextConsumerElement extends Components.ContextConsumer, HTMLStencilElement {}
  var HTMLContextConsumerElement: {
    prototype: HTMLContextConsumerElement;
    new (): HTMLContextConsumerElement;
  };
  interface HTMLElementTagNameMap {
    'context-consumer': HTMLContextConsumerElement
  }

  interface ElementTagNameMap {
    'context-consumer': HTMLContextConsumerElement;
  }
}

