/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  SubscribeCallback,
} from './declarations';

export namespace Components {
  interface ContextConsumer {
    'context': { [key: string]: any };
    'renderer': Function;
    'subscribe'?: SubscribeCallback<any>;
  }
}

declare global {


  interface HTMLContextConsumerElement extends Components.ContextConsumer, HTMLStencilElement {}
  var HTMLContextConsumerElement: {
    prototype: HTMLContextConsumerElement;
    new (): HTMLContextConsumerElement;
  };
  interface HTMLElementTagNameMap {
    'context-consumer': HTMLContextConsumerElement;
  }
}

declare namespace LocalJSX {
  interface ContextConsumer extends JSXBase.HTMLAttributes<HTMLContextConsumerElement> {
    'context'?: { [key: string]: any };
    'renderer'?: Function;
    'subscribe'?: SubscribeCallback<any>;
  }

  interface IntrinsicElements {
    'context-consumer': ContextConsumer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


